version: "3.11"

services:
  backend:
    build: .
    # command: uvicorn main:app --host 0.0.0.0 --port 8001
    ports:
      - 5555:5555
    networks:
      - web
    # volumes:
      # - /etc/letsencrypt/live/api.supercharge.vn/fullchain.pem:/etc/nginx/ssl/cert.pem
      # - /etc/letsencrypt/live/api.supercharge.vn/privkey.pem:/etc/nginx/ssl/private.pem 

  nginx:
    build: ./proxy
    ports:
      - 8080:8080
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      # - /etc/letsencrypt/live/api.supercharge.vn/fullchain.pem:/etc/nginx/ssl/cert.pem
      # - /etc/letsencrypt/live/api.supercharge.vn/privkey.pem:/etc/nginx/ssl/private.pem 
    networks:
      - web

networks:
  web:
    driver: bridge