version: "3.11"

services:
  backend:
    build: .
    ports:
      - 5555:5555
    networks:
      - web
    volumes:
      - /etc/letsencrypt/live/info.supercharge.vn/fullchain.pem:/etc/nginx/ssl/cert.pem
      - /etc/letsencrypt/live/info.supercharge.vn/privkey.pem:/etc/nginx/ssl/private.pem 

  nginx:
    build: ./proxy
    ports:
      - 8899:8899
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/info.supercharge.vn/fullchain.pem:/etc/nginx/ssl/cert.pem
      - /etc/letsencrypt/live/info.supercharge.vn/privkey.pem:/etc/nginx/ssl/private.pem 
    networks:
      - web

networks:
  web:
    driver: bridge