version: '3.8'

services:
  db:
    image: mysql:oracle
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: roottest12344321
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: