name: Build and push Docker image

on:
  push:
    branches: ["main"]

jobs:
  BUILD:
    runs-on: ubuntu-22.04
    steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: Build image
       run: docker build . -t longdnk/service-backend:latest

     - name: Login Docker Hub
       run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}

     - name: Push image to github
       run: docker push longdnk/service-backend:latest

  DEPLOYMENT:
    runs-on: ubuntu-22.04
    needs: BUILD 
    steps:
      - name: Deploy to private server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
            cd ta-backend-deployment 
            docker-compose up -d --build