name: Build and push Docker image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: Build image
       run: docker build . -t longdnk/service-backend:latest

     - name: Login Docker Hub
       run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}

     - name: Push image to github
       run: docker push longdnk/service-backend:latest