name: Build and push Docker image

on:
  push:
    branches: ["main"]

jobs:
  BUILD:
    runs-on: ubuntu-22.04
    steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: Build image
       run: docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/service-backend:latest

     - name: Login Docker Hub
       run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_TOKEN }}

     - name: Push image to github
       run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/service-backend:latest

  DEPLOYMENT:
    runs-on: ubuntu-22.04
    needs: BUILD 
    steps:
      - name: Deploy to private server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          timeout: 1200s
          command_timeout: 1200s 
          port: 22
          script: |
            pwd
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_TOKEN }}
            cd /home/ta-backend-deployment/
            ls -al
            docker-compose down
            docker system prune --all -f
            docker-compose up -d --build